# You can use this file to create a conda environment for this pipeline:
# conda env create -f environment.yml
name: dolphinnext-nanopore-1.0
channels:
   - conda-forge
   - bioconda
   - defaults
dependencies:
   - minimap2=2.17
   - samtools=1.3
   - pycoqc=2.5.2
   - pybedtools=0.8.1
